ingress: https://arbeid.intern.dev.nav.no/arbeid/registrering
basePath: /arbeid/registrering
mocking: disabled
nodeEnv: test
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
amplitude:
  apiKey: 9845ded64c69cd068651cd0d968e0796
  endPoint: amplitude.nav.no/collect
pamJanzzUrl: https://arbeidsplassen.nav.no/pam-janzz/rest
startUrl: https://arbeid.intern.dev.nav.no/arbeid/registrering/start
startRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerordinaerregistrering/
fullforRegistreringSykmeldtUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoersykmeldtregistrering/
reaktiveringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerreaktivering/
sisteArbeidsforholdUrl: http://veilarbregistrering/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://veilarbregistrering/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://veilarbregistrering/veilarbregistrering/api/person/kontaktinfo
dittNAVUrl: https://www.intern.dev.nav.no/minside
dagpengesoknadUrl: https://arbeid.dev.nav.no/dagpenger/dialog/soknad
dialogUrl: https://www.dev.nav.no/arbeid/dialog
featureToggles:
  server: https://unleash.nais.io/api/client/features?tag[]=simple:arbeidssokerregistrering
  client: https://arbeid.intern.dev.nav.no/arbeid/registrering/api/features
hentProfileringUrl: http://veilarbregistrering/veilarbregistrering/api/profilering/
