apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldtregistrering-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "{{basePath}}/api/isalive"
    initialDelay: 3
  readiness:
    path: "{{basePath}}/api/isready"
    initialDelay: 3
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: DEKORATOR_URL
      value: {{dekorator.url}}
    - name: DEKORATOR_ENV
      value: {{dekorator.env}}
    - name: NEXT_PUBLIC_SELF_URL
      value: {{ingress}}
    - name: NEXT_PUBLIC_START_URL
      value: {{startUrl}}
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: {{amplitude.apiKey}}
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: {{amplitude.endPoint}}
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: {{mocking}}
    - name: NEXT_PUBLIC_FEATURETOGGLE_URL
      value: {{featureToggles.client}}
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: {{dittNAVUrl}}
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: {{dagpengesoknadUrl}}
    - name: NEXT_PUBLIC_DIALOG_URL
      value: {{dialogUrl}}
    - name: PAM_JANZZ_URL
      value: {{pamJanzzUrl}}
    - name: START_REGISTRERING_URL
      value: {{startRegistreringUrl}}
    - name: FULLFOR_REGISTRERING_URL
      value: {{fullforRegistreringUrl}}
    - name: FULLFOR_REGISTRERING_SYKMELDT_URL
      value: {{fullforRegistreringSykmeldtUrl}}
    - name: REAKTIVERING_URL
      value: {{reaktiveringUrl}}
    - name: SISTE_ARBEIDSFORHOLD_URL
      value: {{sisteArbeidsforholdUrl}}
    - name: OPPRETT_OPPGAVE_URL
      value: {{opprettOppgaveUrl}}
    - name: KONTAKTINFORMASJON_URL
      value: {{kontaktinformasjonUrl}}
    - name: FEATURE_TOGGLE_URL
      value: {{featureToggles.server}}
    - name: NODE_ENV
      value: {{nodeEnv}}
    - name: HENT_PROFILERING_URL
      value: {{hentProfileringUrl}}
  ingresses:
    - {{ingress}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: arbeidsplassen.nav.no
      rules:
        - application: veilarbregistrering
        - application: nav-dekoratoren
          namespace: personbruker
