ingress: https://www.nav.no/syk/mer-oppfolging
basePath: /syk/mer-oppfolging
mocking: disabled
nodeEnv: production
dekorator:
  url: https://dekoratoren.nav.no/
  env: prod
amplitude:
  apiKey: 913768927b84cde5eac0d0d18c737561
  endPoint: amplitude.nav.no/collect
pamJanzzUrl: https://arbeidsplassen.nav.no/pam-janzz/rest
startUrl: https://www.nav.no/syk/mer-oppfolging/start
startRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerordinaerregistrering/
fullforRegistreringSykmeldtUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoersykmeldtregistrering/
reaktiveringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerreaktivering/
sisteArbeidsforholdUrl: http://veilarbregistrering/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://veilarbregistrering/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://veilarbregistrering/veilarbregistrering/api/person/kontaktinfo
dittNAVUrl: https://www.nav.no/minside
dagpengesoknadUrl: https://www.nav.no/dagpenger/dialog/soknad
dialogUrl: https://www.nav.no/arbeid/dialog
featureToggles:
  server: https://unleash.nais.io/api/client/features?tag[]=simple:arbeidssokerregistrering
  client: https://www.nav.no/syk/mer-oppfolging/api/features
hentProfileringUrl: http://veilarbregistrering/veilarbregistrering/api/profilering/
